apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr
  template:
    metadata:
      labels:
        app: asr
    spec:
      containers:
      - name: asr
        image: asr:latest
        ports:
        - containerPort: 8000
        env:
        - name: ASR_MODEL
          value: "small"
        - name: USE_GPU
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
